print ("Ведите число 1")
Chislo1 = input()
("Введите число 2")
Chislo2 = input()
sum = (int(Chislo1)+int(Chislo2))
raz = (int(Chislo1)-int(Chislo2))
proz =(int(Chislo1)*int(Chislo2))
chas = (int(Chislo1)/int(Chislo2))
print ("Chislo1=",Chislo1,"Chislo2=",Chislo2,"Sum=",sum,"Raz=",raz,"Proz=",proz,"Chas=",chas)